### ISSUE TITLE
[Anon] Bug report: Kingdom_of_Denmark.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/dystopianwars#20]
**File:** Kingdom_of_Denmark.catz

**BattleScribe version:** 1.15.07

**Platform:** Android

**Dropbox:** No

**Description:** Points cost for the asgard battle carrier is currently set to 0 instead of 180.

**Comment by Fuzzi99** [comment]
Fixed a while ago didn't notice bug report sorry
