### ISSUE TITLE
[Anon] Bug report: Prussian_Empire.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/dystopianwars#27]
**File:** Prussian_Empire.catz

**BattleScribe version:** 2.00.26

**Platform:** Android

**Dropbox:** Yes

**Description:** Any chance you could add the new Eider mk 1 and 2 into the prussian empire?

**Comment by Fuzzi99** [comment]
They will be added once the new rules release in a few weeks when I rewrite the entire system from the ground up
