### ISSUE TITLE
[Join Request] Hi, since a group of my friends use battlescribe and we used to use it in the past I would like to help with the new rules

### ISSUE THREAD

**Issue by kolhammer** [BSData/dystopianwars#33]
Hello,

I would like to help with contributions for the new Dystopian Wars and help maintain the rules with the latest orbats to help myself, friends and others who enjoy the new releases coming out in Dystopian wars.

Best Regards,

Kolhammer

**Comment by DrTobogganMD** [comment]
Hello, @kolhammer. Please accept the invitation in the email or on the [webpage][invitation]. Welcome aboard!

Don't forget to read through [wiki][], there are some useful guides, especially [Data Author Guide][guide].

Also, join the data author community over at discord!

[![Chat on Discord](https://img.shields.io/discord/558412685981777922.svg?logo=discord&style=popout-square)](https://discord.gg/KqPVhds)

Cheers!

[invitation]: https://github.com/BSData/dystopianwars/invitations
[wiki]: https://github.com/BSData/catalogue-development/wiki
[guide]: https://github.com/BSData/catalogue-development/wiki/Data-Author-Guide
