### ISSUE TITLE
[Join Request]

### ISSUE THREAD

**Issue by Ravagraid** [BSData/dystopianwars#34]
Hello, is it at all possible to become a collaborator on this repo?

**Comment by amis92** [comment]
@siponer Are you still in touch with this repository, or can I invite @Ravagraid ?

**Comment by siponer** [comment]
I can accept amy contributors. Send mail to siponeric@hotmail.com so we can manager the activity

**Comment by siponer** [comment]
Ravagraid I invite you so you will be able to download the Datafile you have created or you can collaborate to the management of the old one.

If it is possible I want to test with you your job them before publish.

**Comment by siponer** [comment]
@Ravagraid Can we discuss about the collaboration?

**Comment by siponer** [comment]
@amis92 the invitation seems not working!!

**Comment by Ravagraid** [comment]
Hello, yes. We can discuss it.

**Comment by siponer** [comment]
waiting the invitation works @Ravagraid which faction you want to manage or correct?

**Comment by Ravagraid** [comment]
I was wanting to manage the Crown faction.

**Comment by siponer** [comment]
While we are waiting you to join the reporitory as collaborator, I  attach here The Crown datafile I have started so you can continue the work
[The Crown.zip](https://github.com/BSData/dystopianwars/files/7533278/The.Crown.zip)
