### ISSUE TITLE
[Anon] Bug report: The Imperium.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/dystopianwars#36]
**File:** The Imperium.catz

**BattleScribe version:** 2.03.25

**Platform:** Android

**Dropbox:** No

**Description:** Imperium roster. When selecting reiter flak cruiser it has the template for augustus bombardment cruiser below. Correct points cost for additional ship however

**Comment by siponer** [comment]
Bug solved in 3.05.00 release
