### ISSUE TITLE
[Anon] Bug report: Commonwealth.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/dystopianwars#38]
**File:** Commonwealth.catz

**BattleScribe version:** 2.03.25

**Platform:** Android

**Dropbox:** No

**Description:** Mozhayski marked 235 - should be 230
Ruriks frigates marked at 88 - should be 80
Norilsk cruisers marked at 112 - should be 118.

Thank you once again

**Comment by siponer** [comment]
Correction done
