### ISSUE TITLE
incorect data for Krykun Shockwave Frigate

### ISSUE THREAD

**Issue by googleisaace** [BSData/dystopianwars#40]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Device and data (please complete the following information):**
 - OS: [desktop]
 - BattleScribe version [dystopian wars 3.09]
 - Release version [e.g. v1.2.3]

**Additional context**
the correct values are 80 points for the unit (2 models)  and a additional 40 pts per model (up to 2 additional models)

**Comment by siponer** [comment]
Bug fixed. To be publishe
