### ISSUE TITLE
Imperium data corrections

### ISSUE THREAD

**Issue by kamkazekid** [BSData/dystopianwars#44]
**Imperium Support Battlefleet**
Demands to have 1 or more Sigimer-class Destroyers, when not true.

The cost of additional Lightning Raid tokens states 20, when it is 15 points

**Gustav Twin Bombard**
Doesn't exist in this Battlescribe update.

**Bertha Heavy Bombard**
Doesn't exist in this Battlescribe update

**SMS Brandenburg**
Incorrect points cost. States 270, when it should be 250

**SMS Tirpitz**
The generator decreases the cost by 10 points, when it shouldn't

**Ice Maiden Dreadnought Super-Carrier**
Incorrect points cost. States 545. Is in fact 535.

**Valhalla Fast Dreadnought**
Incorrect points cost. States 366. Is in fact 348.

**SMS Danegeld**
Doesn't exist in the Battlescribe update

**SMS Eiskalte Schoenheit**
Incorrect points cost. States 575. Is in fact 555

**SMS Prinzessin Wilhelmina**
Incorrect points cost. States 625. Is in fact 570

**SMS Terra Mariana**
Unit doesn't exist in this update.

**Eltz Offshore Support Platform**
Incorrect points cost. States 69. Is in fact 68.

**Gungnir Raider**
Incorrect points cost. States 72. Is in fact 73.

**SMS Holtzendorff/Heidelberg Logistics Battlecruiser**
Incorrect points cost. States 230. Is in fact 205.
There is no SMS Holtzendorff, only the Holtzendorff-pattern for the Heidelberg

**Hochmeister Vitruvian Colossus**
SUBMARAUDER rule isn't included

**Hoth Heavy Corvette**
Incorrect points cost. States 66. Is in fact 64

**Jotunn Heavy Raider**
Incorrect points cost. States 111. Is in fact 113

**Loki Shadow Raider**
Incorrect points cost. States 110. Is in fact 113

**Malus Shock Rocket Frigate**
No longer exists in the ORBAT. Have been replaced with the Malus Anti-Air Destroyers

**Metzger Vitruvian Colossus**
SUBMARAUDER rule isn't included

**Nachtsturm Flak Frigates**
Doesn't exist in this Battlescribe update

**Odin Reaver**
Incorrect points cost. States 96. Is in fact 90.

**Sigimer Destroyer**
Incorrect points cost. States 74. is in fact 72

Along with various changes needed to a couple rules.

**Comment by siponer** [comment]
Bug solved in the version 3.03.13
