### ISSUE TITLE
[Anon] Bug report: Enlightened.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/dystopianwars#63]
**File:** Enlightened.catz

**BattleScribe version:** 2.03.27

**Platform:** Android

**Dropbox:** No

**Description:** Validation issues with Cetacean Support Battlefleet
* Create a new Cetacean Support Battlefleet
* Add a Decartes flagship and 1x Vesalius surface unit
* Add 1x Physeter Assault token (quantity 1)

Validation says that a minimum of 1x Vesalius is requied, despite this being present. Adding more doesn't fix this, so may be an ID/naming issue in the check
Validation says that minimum of 2x Physeter tokens required, despite only one battlefleet in the force present that has this rule (ORBAT says one token per battlefleet with this rule +  max of 4 additional tokens at +12pts per token, so I think the logic is counting the originating battlefleet twice)

Corollary - I am new to the game so may have missed some subtlety to the Physeter tokens, I just can't spot it though

**Comment by siponer** [comment]
Closed in verion 3.19.01

**Comment by siponer** [comment]
Closed in Enlightened v11
