### ISSUE TITLE
Descartes in Faction or Cetacean Battlefleet requires, but can't have Physeter Ambush

### ISSUE THREAD

**Issue by racock** [BSData/dystopianwars#64]
**Describe the bug**
Adding a Descartes Control Ship to either an Enlightened Faction Battlefleet or Cetacean Operations Battlefleet generates an error that can't be cleared with available options

**To Reproduce**
1. Add an Enlightened Faction Battlefleet or a Cetacean Operations Battlefleet
2. Add a Descartes Control Ship as the flagship
3. See error
"Enlightened v3.03 v11 (+245 Descartes Control Ship Enlightened Faction Battlefleet must have 1 more selections of Physeter Ambush"
Error also for any other Battlefleet's previously added even though they don't contain the Descartes Control Ship

**Expected behavior**
Ability to add Physeter Construct tokens/ Orca Construct tokens to available units e.g Descartes Control Ship
AND
remove error check requiring at least one Physeter Construct Token (the unit automatically generates 5/3 per turn) and can upgrade these to Orca Construct Tokens at +10 points each.

**Screenshots**
I'll try to add in a mo

**Device and data (please complete the following information):**
 - OS: IOS
 - BattleScribe version 2.03.15
 - Release version v3.03 v11

**Additional context**

**Comment by racock** [comment]
![image](https://github.com/BSData/dystopianwars/assets/137170279/3936e159-01be-4921-9266-9e4c961fbb1d)

**Comment by siponer** [comment]
corrected in Enlightened 3.03 v12

**Comment by racock** [comment]
You sir, are a star!

Thank you for your hard work on this one.

If there’s anything I can help with other than calling out bugs, please let me know.

Richard Acock


On 2 Jul 2023, at 07:08, Riccardo Sipone ***@***.***> wrote:

﻿

Closed #64<https://github.com/BSData/dystopianwars/issues/64> as completed.

**Comment by siponer** [comment]
Hello,
Thanks a lot for you mail.
In this moment the best way to help me i to test the datafiles waiting the new version.
When the new version will be publish, if you jave understand how the editing works you cen help me to update.

See you!!


Inviato da Posta<https://go.microsoft.com/fwlink/?LinkId=550986> per Windows

Da: ***@***.***>
Inviato: domenica 2 luglio 2023 16:15
A: ***@***.***>
Cc: Riccardo ***@***.***>; State ***@***.***>
Oggetto: Re: [BSData/dystopianwars] Descartes in Faction or Cetacean Battlefleet requires, but can't have Physeter Ambush (Issue #64)

You sir, are a star!

Thank you for your hard work on this one.

If there’s anything I can help with other than calling out bugs, please let me know.

Richard Acock


On 2 Jul 2023, at 07:08, Riccardo Sipone ***@***.***> wrote:

﻿

Closed #64<https://github.com/BSData/dystopianwars/issues/64> as completed.
