### ISSUE TITLE
typo in Merian Figate Squadron

### ISSUE THREAD

**Issue by racock** [BSData/dystopianwars#65]
**Describe the bug**
Merian Frigate is missing an 'r'

**To Reproduce**
1. Look at Enlightened army units

**Expected behavior**
corrected spelling

**Screenshots**
![image](https://github.com/BSData/dystopianwars/assets/137170279/de1322c2-a598-4871-abee-2699467be298)

**Device and data (please complete the following information):**
 - OS: iOS
 - BattleScribe version 2.03.15
 - Release version v3.03 v11

**Additional context**

**Comment by siponer** [comment]
corrected in Enlightened 3.03 c12
