### ISSUE TITLE
[Anon] Bug report: Enlightened.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/dystopianwars#66]
**File:** Enlightened.catz

**BattleScribe version:** 2.03.27

**Platform:** Android

**Dropbox:** No

**Description:** According to the 3.03 ORBAT, the Enlightened Support Battlefleet is allowed to take up to two Aerial units
Create an Enlightened Support Battlefleet, and add a PythusSquadron and a Valtar squadron - you receive a validation error saying the fleet "has 1 too many selections of Valtar, maximum 1"

This doesn't seem to appear for any other combinations of aerial units in the Support battlefleet, only this specific pairing

**Comment by siponer** [comment]
closed in 3.19.03
