### ISSUE TITLE
Bug : can't add escort to Yamaguchi Squadron in Empire fleet

### ISSUE THREAD

**Issue by Lilan-Fr** [BSData/dystopianwars#69]
**Describe the bug**
You can't add Chita Escort to the Yamaguchi squadron

**To Reproduce**
1. Go to 'Japanese Frontline Battlefleet in Empire Roster'
2. Click to add 'Yamaguchi Cruiser'
3. Go to "Escort Model' in the rigth column
4. There is no box to add escort

**Expected behavior**
Yamaguchi suqadron should be able to take Chita escorts.

**Screenshots**

**Device and data (please complete the following information):**
 - OS: Windows X
 - App being used to create lists Battlescribe v 2.03.21
 - Data release version v 3.20.15 (2024 Jan 8)

**Comment by Lilan-Fr** [comment]
I found the bug source : the ship miss the "Japanese" categorie in Root Entry Selection.

**Comment by siponer** [comment]
Done
