### ISSUE TITLE
Bug : can't add Chita to Ofukoro

### ISSUE THREAD

**Issue by Lilan-Fr** [BSData/dystopianwars#70]
Describe the bug
You can't add Chita Escort to Offokuro Ika Colossus Squadron

To Reproduce

    Go to 'Japanese Frontline Battlefleet in Empire Roster'
    Click to add 'Ofukoro Ika Colossus Squadronr'
    Go to "Escort Model' in the rigth column
    There is no box to add escort

Expected behavior
Ofukoro Ika Colossus Squadron should be able to take Chita escorts.

Device and data (please complete the following information):

    OS: Windows X
    App being used to create lists Battlescribe v 2.03.21
    Data release version v 3.20.15 (2024 Jan 8)

Other information : issue not hapenning with Kaiju Ika Colossus Squadron

**Comment by Lilan-Fr** [comment]
I found the bug source : the ship miss the "Japanese" categorie in Root Entry Selection.

**Comment by siponer** [comment]
Done
