### ISSUE TITLE
Bug : Mizushi exosub SRS capacity is mistaken

### ISSUE THREAD

**Issue by Lilan-Fr** [BSData/dystopianwars#71]
**Describe the bug**
In the Empire Orbat, the Mizushi exosub SRS capacity is 2/1. It should be 3/1 as per the rules

**To Reproduce**
1. Open an empire Orbat
2. Look for the Mizushi subarine in the left coluù
3. Open "Preview"

OS: Windows X
App being used to create lists Battlescribe v 2.03.21
Data release version v 3.20.15 (2024 Jan 8)

**Comment by siponer** [comment]
Done
