### ISSUE TITLE
Ning Jing Battleship equipment

### ISSUE THREAD

**Issue by Nugget909** [BSData/dystopianwars#77]
**Is your feature request related to a problem? Please describe.**
Empire v3.06 v13 Catalogue, Ning Jing Battleship. Unit cannot deselect a Heavy Gun Battery mount to select a generator per pg.17 of the Empire Orbat. When selecting any Chinese Flagship as part of a Battlefleet - excluding Empire Faction Battlefleet - selecting an escort, aside from a Chita Escort, is reported as a roster error.

**Describe the solution you'd like**
Add "None" selection to Heavy Gun Battery selectors for Ning Jing Battleship to allow selecting generators without error. Remove error when selecting standard escort tokens for Chinese flagships.

**Comment by siponer** [comment]
I'll fix in next release with other correction

**Comment by siponer** [comment]
Corrected

**Comment by siponer** [comment]
Corrected in the release 3.20.3
