### ISSUE TITLE
Price incorrect for Dead Presidents

### ISSUE THREAD

**Issue by Barrdyn** [BSData/dystopianwars#78]
**Describe the bug**
The price supplied for the Dead Presidents is currently wrong.

**To Reproduce**
1. Go to Union
2. Check Surface Units
3. Scroll down to The Dead Presidents

**Expected behavior**
They should be a point cost of 474 (base, before additional points costs), but instead display in the thousands.

**Screenshots**
![image](https://github.com/user-attachments/assets/cd91b18e-c33b-492f-ae79-c3a1cfc649c8)

**Device and data (please complete the following information):**
 - OS: Android and Windows
 - New Recruit App and Website
 - App version 3.0.7a
 - Data release version Current

**Comment by InsaneCheese** [comment]
![Union catz](https://github.com/user-attachments/assets/7afcc5ca-00ea-4f42-9f19-9b8f272111d7)

I've fixed it in this file, just rename it to .catz and drop it in the DW data folder. You'll have to delete any Dead Presidents in your list and readd them to refresh.

If you delete the yellow highlighted lines in the Union file it stops adding 3 of each variant and has the correct costs and profiles.

![Screenshot 2024-10-10 203502](https://github.com/user-attachments/assets/d9d152f2-15ad-4c75-8070-9ddc0582c4e4)

**Comment by siponer** [comment]
Fixed!!!!

**Comment by Barrdyn** [comment]
Thank you kindly for this fix!
