### ISSUE TITLE
[Anon] Union v3.07a: Adds 6 copies of each ship and you can't edit the amount 

### ISSUE THREAD

**Issue by NewRecruitAnon** [BSData/dystopianwars#79]
**Problem:**
Adds 6 copies of each ship and you can't edit the amount 

**Expected:**
A single copy of each ship

**List:** https://www.newrecruit.eu/app/list/5QmUe
**Unit:** The Dead Presidents, id: cc3d-570f-e0b8-59f7

**Comment by siponer** [comment]
Corrected!!!
