### ISSUE TITLE
[Anon] Crown v3.06a: Excalibur heavy destroyer speed is listed as 10 but only 9

### ISSUE THREAD

**Issue by NewRecruitAnon** [BSData/dystopianwars#80]
**Problem:**
Excalibur heavy destroyer speed is listed as 10 but only 9

**Expected:**
Needs to be reduced by 1

 **Additional Info:**
Crown orbat v306a

**List:** https://www.newrecruit.eu/app/list/R4t9A

**Comment by siponer** [comment]
Fixed
