### ISSUE TITLE
[Anon] Union v3.07a: The Dead President Point cost is wrong, The cost too high

### ISSUE THREAD

**Issue by NewRecruitAnon** [BSData/dystopianwars#81]
**Problem:**
The Dead President Point cost is wrong, The cost too high

**Expected:**
Cost from separate variants or choose between the two variants

 **Additional Info:**
Orbat Union

**List:** https://www.newrecruit.eu/app/list/fM6jd

**Comment by siponer** [comment]
Corrected!!!!
