### ISSUE TITLE
[Anon] Sultanate v3.07: Hirka Skycutter Squadron has either a numeral or unicode that breaks formatting

### ISSUE THREAD

**Issue by NewRecruitAnon** [BSData/dystopianwars#82]
**Problem:**
Hirka Skycutter Squadron has either a numeral or unicode that breaks formatting

**Expected:**
The name to have an 'i' instead of a '1' or whatever is in the place.

 **Additional Info:**
When exporting to PDF, whatever character that is instead causes the parser to cause odd spacing and misplace fields.

**List:** https://www.newrecruit.eu/app/list/HHEuK

**Comment by siponer** [comment]
Fixed putting a "i" instead of the original Turkish letter.
